# Array

Un array es una estructura de datos en NumPy que permite almacenar y procesar un conjunto de elementos del mismo tipo de datos. Los arrays de NumPy son similares a las listas de Python, pero ofrecen un rendimiento mucho mejor y un conjunto más completo de funciones y operaciones matemáticas.

Un array de NumPy se puede crear a partir de una lista de Python utilizando la función **np.array()**. 

Veamos el siguiente código de Python donde se usan los **arrays**:

In [1]:
# Importa la biblioteca NumPy
import numpy as np

In [2]:
# Creamos una lista de enteros llamada "list" y la imprimimos.
list = [1,2,3,4,5,6,7,8,9]
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
# Convertimos la lista "list" en un array de NumPy llamada "arr"
arr = np.array(list)

In [4]:
# Imprimimos el tipo de datos del array "arr"
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
# Creamos una lista de listas (matriz) llamada "matriz" y la imprimimos junto a una linea de separación
matriz = [[1,2,3],[4,5,6],[7,8,9]]
print(matriz)
print("-"*10)

# Convertimos la matriz en un array de NumPy e imprimimos el array.
matriz = np.array(matriz)
print(matriz)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Indexing

El indexado es una técnica en Python que se utiliza para acceder a un elemento o subconjunto de elementos de una secuencia (como una lista, una cadena de caracteres o un array) utilizando un índice o un rango de índices.

En Python, los índices comienzan en cero para la mayoría de las secuencias, lo que significa que el primer elemento de una secuencia tiene índice 0, el segundo elemento tiene índice 1, y así sucesivamente. También se pueden usar índices negativos, que cuentan desde el final de la secuencia hacia atrás. Por ejemplo, el último elemento de una secuencia tiene índice -1, el penúltimo elemento tiene índice -2, y así sucesivamente.

Para acceder a un elemento de una secuencia utilizando su índice, se utiliza la sintaxis **sequence[index]**. Por ejemplo:

In [6]:
# Acceder al primer elemento de una lista
my_list = [1, 2, 3, 4]
first_element = my_list[0]  # first_element es 1
print(first_element)

# Acceder al último elemento de una lista
last_element = my_list[-1]  # last_element es 4
print(last_element)

# Acceder al segundo elemento de una cadena de caracteres
my_string = "Hello"
second_char = my_string[1]  # second_char es "e"
print(second_char)


1
4
e


Veamos más ejemplos de indexado:

In [7]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[0]

1

In [9]:
arr[0] + arr[5]

7

In [10]:
matriz[0]

array([1, 2, 3])

In [11]:
matriz[2]

array([7, 8, 9])

In [12]:
matriz[2,2]

9

### Slicing

El slicing es una técnica en Python que se utiliza para obtener un subconjunto de elementos de una secuencia (como una lista, una cadena de caracteres o un array) utilizando un rango de índices. El slicing es similar al indexado en Python, pero en lugar de acceder a un solo elemento, el slicing permite acceder a un conjunto de elementos de forma más concisa.

Para utilizar el slicing, se utiliza la sintaxis **`sequence[start:end:step]`**, donde **`start`** es el índice del primer elemento del subconjunto, **`end`** es el índice del primer elemento que no está incluido en el subconjunto y **`step`** es el tamaño del salto entre elementos. Por ejemplo:

In [13]:
# Obtener los primeros tres elementos de una lista
my_list = [1, 2, 3, 4, 5]
sublist = my_list[:3]  # sublist es [1, 2, 3]
print(sublist)

# Obtener los últimos tres elementos de una lista
sublist = my_list[-3:]  # sublist es [3, 4, 5]
print(sublist)

# Obtener un subconjunto intermedio de una cadena de caracteres
my_string = "Hello World"
substring = my_string[6:11]  # substring es "World"
print(substring)

[1, 2, 3]
[3, 4, 5]
World


Si se omite el valor de **start**, se asume que es el primer elemento de la secuencia. Si se omite el valor de **end**, se asume que es el último elemento de la secuencia. Si se omite el valor de **step**, se asume que es 1.

También se puede utilizar el slicing para recorrer una secuencia en orden inverso, utilizando un valor negativo para step. Por ejemplo:

In [14]:
# Obtener los primeros tres elementos de una lista en orden inverso
my_list = [1, 2, 3, 4, 5]
sublist = my_list[3:0:-1]  # sublist es [4, 3, 2]
print(sublist)

# Obtener todos los elementos de una lista en orden inverso
sublist = my_list[::-1]  # sublist es [5, 4, 3, 2, 1]
print(sublist)

# Obtener un subconjunto intermedio de una cadena de caracteres en orden inverso
my_string = "Hello World"
substring = my_string[10:5:-1]  # substring es "dlroW"
print(substring)

[4, 3, 2]
[5, 4, 3, 2, 1]
dlroW


Veamos más ejemplos de "slicing":

In [15]:
arr[0:3]

array([1, 2, 3])

In [16]:
arr[:3]

array([1, 2, 3])

In [17]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr[::3]

array([1, 4, 7])

In [20]:
arr[-1]

9

In [21]:
arr[-3:]

array([7, 8, 9])

In [22]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [24]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])