# Data types

NumPy proporciona un conjunto de tipos de datos que se pueden utilizar para especificar el tipo de datos de los elementos de un array. Algunos de los tipos de datos más comunes en NumPy son:

* bool: representa valores booleanos (verdadero o falso).
* int8: representa números enteros de 8 bits con signo.
* int16: representa números enteros de 16 bits con signo.
* int32: representa números enteros de 32 bits con signo.
* int64: representa números enteros de 64 bits con signo.
* uint8: representa números enteros sin signo de 8 bits.
* uint16: representa números enteros sin signo de 16 bits.
* uint32: representa números enteros sin signo de 32 bits.
* uint64: representa números enteros sin signo de 64 bits.
* float16: representa números de punto flotante de 16 bits.
* float32: representa números de punto flotante de 32 bits (también conocidos como "float").
* float64: representa números de punto flotante

In [1]:
import numpy as np

## INT

In [11]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [13]:
arr

array([1, 2, 3, 4])

In [14]:
arr.dtype

dtype('int64')

Qué pasa si el tipo de dato no se ajusta a lo que necesitamos ?

## FLOAT

In [15]:
arr1 = np.array([1,2,3,4], dtype='float64')
print(arr1)

[1. 2. 3. 4.]


In [16]:
arr1

array([1., 2., 3., 4.])

In [17]:
arr1.dtype

dtype('float64')

Para cambia el tipo de dato...

In [18]:
arr

array([1, 2, 3, 4])

In [19]:
arr.astype(np.float64)

array([1., 2., 3., 4.])

Veamos otro cambio

In [20]:
arr2 = np.array([0, 1, 2, 3, 4])
arr2 = arr2.astype(np.bool_)
arr2

array([False,  True,  True,  True,  True])

In [22]:
arr3 = np.array([0, 1, 2, 3, 4])
arr3 = arr3.astype(np.string_)
arr3

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [23]:
arr4 = np.array(["0", "1", "2", "3", "4"])
arr4 = arr4.astype(np.int8)
arr4

array([0, 1, 2, 3, 4], dtype=int8)

Mas información sobre tipos de datos: https://numpy.org/doc/stable/user/basics.types.html