In [1]:
import numpy as np


In [4]:
arr = np.linspace(1,10, 10, dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [5]:
indices_cond = arr > 5

In [8]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [9]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [10]:
arr[(arr > 5)] = 99

In [11]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [13]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)

Con las condicionales se logra filtrar data frames, arreglos o diferentes objetos de estructuras de datos.