# Create Arrays

In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand()

0.3389809045252373

In [15]:
np.random.rand(4)

array([0.96567868, 0.17678202, 0.07296556, 0.21929615])

In [16]:
np.random.rand(4,4)

array([[0.06969835, 0.63067804, 0.36547524, 0.59050391],
       [0.54579282, 0.0540418 , 0.8586681 , 0.58114115],
       [0.39776983, 0.25217681, 0.61578733, 0.1585259 ],
       [0.66947745, 0.77375545, 0.69341194, 0.84281854]])

In [18]:
np.random.randint(1,15)

14

In [19]:
np.random.randint(1,100,(10,10))

array([[24, 90, 68, 23, 35, 46, 42, 32, 87, 23],
       [81, 53, 96, 68,  2, 70, 40, 94, 25, 81],
       [24, 65, 91, 75, 50, 90,  3, 32, 96, 84],
       [89, 98, 39, 10, 13, 87, 27,  6, 79, 84],
       [47, 53, 63, 58, 34, 55, 59, 69, 88, 20],
       [52, 53, 46,  8, 58, 98, 99, 91, 62, 95],
       [88, 97, 64, 13, 70, 94, 99, 35, 21, 89],
       [17, 80, 52,  4, 46,  1, 92,  6, 37, 85],
       [53, 83, 73, 64, 70, 27, 66, 82, 25, 81],
       [67, 13, 46, 71, 77, 15, 22, 67, 42, 71]])