# Shape & Reshape


In [1]:
import numpy as np

Crear un arreglo llamado "arr", con numeros aleatoreos de 1 a 10 (sin incluir 10), con una forma de 3 filas, 2 columnas.

In [2]:
arr = np.random.randint(1, 10, (3,2))
print(arr)

[[8 7]
 [3 3]
 [1 3]]


In [3]:
arr.shape

(3, 2)

Cambiar la forma de "arr" a una fila, 6 columnas.

In [4]:
arr.reshape(1,6)

array([[8, 7, 3, 3, 1, 3]])

Cambiar la forma de "arr" a dos filas, 3 columnas.

In [5]:
arr.reshape(2,3)

array([[8, 7, 3],
       [3, 1, 3]])

El método **numpy.reshape()** es una función de la librería de Python **NumPy** que permite cambiar la forma o el tamaño de una matriz o un vector. En este caso, el código **np.reshape(arr, (1,6))** está cambiando la forma del array arr a una matriz de una fila y seis columnas.

La función numpy.reshape() toma dos argumentos:

**arr:** es el array que queremos cambiar de forma.
**(1,6)**: es una tupla que indica la forma deseada para el array. En este caso, se está especificando una matriz con una fila y seis columnas.

In [6]:
np.reshape(arr, (1,6))

array([[8, 7, 3, 3, 1, 3]])

In [7]:
arr

array([[8, 7],
       [3, 3],
       [1, 3]])

In [9]:
np.reshape(arr, (2,3), "C")

array([[8, 7, 3],
       [3, 1, 3]])

In [10]:
np.reshape(arr, (2,3), "F")

array([[8, 1, 3],
       [3, 7, 3]])

In [14]:
np.reshape(arr, (2,3), "A")

array([[8, 7, 3],
       [3, 1, 3]])