# Funciones Principales en Numpy

Algunas de las funciones más comunes de NumPy son:

1. **np.array**: permite crear un arreglo NumPy a partir de una lista o tupla de Python.
2. **np.zeros**: permite crear un arreglo NumPy de ceros con una forma dada.
3. **np.ones**: permite crear un arreglo NumPy de unos con una forma dada.
4. **np.arange**: permite crear un arreglo NumPy con un rango de valores específico.
5. **np.linspace**: permite crear un arreglo NumPy con un número específico de elementos en un rango dado.
6. **np.random.rand**: permite crear un arreglo NumPy con valores aleatorios en el intervalo [0, 1].
7. **np.random.randn**: permite crear un arreglo NumPy con valores aleatorios que siguen una distribución normal estándar.
8. **np.empty**: permite crear un arreglo NumPy sin inicializar sus elementos.
9. **np.eye**: permite crear una matriz identidad NumPy.
10. **np.full**: permite crear un arreglo NumPy con un valor específico en todos sus elementos.

Veamos algunos ejemplos en el siguiente códido:

In [1]:
# importamos la librería numpy
import numpy as np

In [2]:
# generamos un arreglo de 10 números aleatorios enteros entre 1 y 20
arr = np.random.randint(1, 20, 10)
print(arr)

[ 3 15  1 14 15  7 10 11 10 15]


In [3]:
# convertimos el arreglo en una matriz de 2 filas y 5 columnas
matriz = arr.reshape(2,5)
print(matriz)

[[ 3 15  1 14 15]
 [ 7 10 11 10 15]]


In [4]:
# imprimimos el arreglo original
print(arr)
print("="*10)

# imprimimos el valor máximo del arreglo
print(arr.max(), "--> valor máximo del arreglo")
print("-"*10)

# imprimimos el índice del valor máximo del arreglo (si hay varios, toma el menor índice)
print(arr.argmax())
print("="*10)

# imprimimos el valor mínimo del arreglo
print(arr.min(), "--> valor mínimo del arreglo")
print("-"*10)

# imprimimos el índice del valor mínimo del arreglo (si hay varios, toma el menor índice)
print(arr.argmin())
print("="*10)

# obtenemos el rango del arreglo (valor máximo - valor mínimo)
print(arr.ptp(), "--> rango entre valores: máximo y mínimo")
print("="*10)

# obtenemos el percentil 50 (mediana) del arreglo "arr"
print(np.sort(arr), "--> arreglo ordenado de menor a mayor")
print(np.percentile(arr,50), "--> percentil 50 del arreglo (mediana)")

# obtenemos la mediana del arreglo con la función median de numpy
print(np.median(arr), "--> mediana del arreglo")

# imprimimos la desviación estándar del arreglo
print(np.std(arr), "--> desviación estandar")

# imprimimos la varianza del arreglo
print(np.var(arr), "--> varianza")

# imprimimos el promedio (media) del arreglo
print(np.mean(arr), "--> promedio")

[ 3 15  1 14 15  7 10 11 10 15]
15 --> valor máximo del arreglo
----------
1
1 --> valor mínimo del arreglo
----------
2
14 --> rango entre valores: máximo y mínimo
[ 1  3  7 10 10 11 14 15 15 15] --> arreglo ordenado de menor a mayor
10.5 --> percentil 50 del arreglo (mediana)
10.5 --> mediana del arreglo
4.805205510693585 --> desviación estandar
23.089999999999996 --> varianza
10.1 --> promedio


La función **ptp** de NumPy (peak-to-peak) nos permite obtener el rango de un arreglo, es decir, la diferencia entre el valor máximo y el valor mínimo del arreglo.

La función **percentile** de NumPy nos permite obtener el percentil de un arreglo dado, es decir, el valor del arreglo que se encuentra en una posición dada en términos de porcentaje. 

La función **median** de NumPy nos permite obtener la mediana de un arreglo, es decir, el valor que se encuentra en la mitad del arreglo (si está ordenado).

La función **std** de NumPy nos permite obtener la desviación estándar de un arreglo, que es una medida de dispersión que nos indica cuánto varían los valores del arreglo respecto a la media. 

La función **var** de NumPy nos permite obtener la varianza de un arreglo, que es otra medida de dispersión que nos indica cuánto varían los valores del arreglo respecto a la media.

La función **mean** de NumPy nos permite obtener el promedio de un arreglo, que es la suma de todos los valores del arreglo dividida por el número de elementos.

In [5]:
# imprimimos la matriz
print(matriz)
print("="*10)

# imprimimos el valor máximo de la matriz
print(matriz.max(), "--> valor máximo de la matriz")
print("-"*10)

# imprimimos el índice del valor máximo de la matriz
print(matriz.argmax())
print("="*10)

# imprimimos el valor mínimo de la matriz
print(matriz.min(), "--> valor mínimo de la matriz")
print("-"*10)

# imprimimos el índice del valor mínimo de la matriz
print(matriz.argmin())
print("="*10)

# obtenemos el rango de la matriz (valor máximo - valor mínimo)
print(matriz.ptp(), "--> valor ptp de la matriz")
print("="*10)

# obtenemos el percentil 50 (mediana) de la matriz
print(np.sort(matriz), "--> arreglo ordenado de menor a mayor por cada fila")
print(np.percentile(matriz,50), "--> percentil 50 del arreglo (mediana)")

# obtenemos la mediana de la matriz con la función median de numpy
print(np.median(matriz), "--> mediana del arreglo")

# imprimimos la desviación estándar de la matriz
print(np.std(matriz), "--> desviación estandar")

# imprimimos la varianza de la matriz
print(np.var(arr), "--> varianza")

# imprimimos el promedio (media) de la matriz
print(np.mean(matriz), "--> promedio")

[[ 3 15  1 14 15]
 [ 7 10 11 10 15]]
15 --> valor máximo de la matriz
----------
1
1 --> valor mínimo de la matriz
----------
2
14 --> valor ptp de la matriz
[[ 1  3 14 15 15]
 [ 7 10 10 11 15]] --> arreglo ordenado de menor a mayor por cada fila
10.5 --> percentil 50 del arreglo (mediana)
10.5 --> mediana del arreglo
4.805205510693585 --> desviación estandar
23.089999999999996 --> varianza
10.1 --> promedio


In [6]:
# volvemos a imprimir la matriz
print(matriz)
print("="*10)

# imprimimos el valor máximo de cada columna de la matriz
print(matriz.max(0), "--> valor máximo x columna")
print("-"*10)

# imprimimos el índice de fila del valor máximo para cada columna de la matriz
print((matriz.argmax(0)), "--> indice de fila del valor máximo para cada columna de la matriz")
print("="*10)

# imprimimos el valor mínimo de cada columna de la matriz
print(matriz.min(0), "--> valor mínimo x columna")
print("-"*10)

# imprimimos el índice de fila del valor máximo de cada columna de la matriz
print((matriz.argmin(0)), "--> indice de fila del valor mínimo para cada columna de la matriz")
print("="*10)

# obtenemos el rango de la matriz (valor máximo - valor mínimo)
print(matriz.ptp(0), "--> valor ptp de la matriz por cada columna de la matriz")
print("="*10)

# obtenemos el percentil 50 (mediana) de la matriz
print(np.sort(matriz,0), "--> arreglo ordenado de menor a mayor por cada columna")
print(np.percentile(matriz,50), "--> percentil 50 del arreglo (mediana)")

# obtenemos la mediana de la matriz con la función median de numpy
print(np.median(matriz), "--> mediana del arreglo")

# imprimimos la desviación estándar de la matriz
print(np.std(matriz), "--> desviación estandar")

# imprimimos la varianza de la matriz
print(np.var(arr), "--> varianza")

# imprimimos el promedio (media) de la matriz
print(np.mean(matriz), "--> promedio")

[[ 3 15  1 14 15]
 [ 7 10 11 10 15]]
[ 7 15 11 14 15] --> valor máximo x columna
----------
[1 0 1 0 0] --> indice de fila del valor máximo para cada columna de la matriz
[ 3 10  1 10 15] --> valor mínimo x columna
----------
[0 1 0 1 0] --> indice de fila del valor mínimo para cada columna de la matriz
[ 4  5 10  4  0] --> valor ptp de la matriz por cada columna de la matriz
[[ 3 10  1 10 15]
 [ 7 15 11 14 15]] --> arreglo ordenado de menor a mayor por cada columna
10.5 --> percentil 50 del arreglo (mediana)
10.5 --> mediana del arreglo
4.805205510693585 --> desviación estandar
23.089999999999996 --> varianza
10.1 --> promedio


In [7]:
# volvemos a imprimir la matriz
print(matriz)
print("="*10)

# imprimimos el valor máximo de cada fila de la matriz
print(matriz.max(1), "--> valor máximo x fila")
print("-"*10)

# imprimimos el índice del valor máximo de cada fila de la matriz
print(matriz.argmax(1), "--> indice de columna del valor máximo para cada fila de la matriz")
print("="*10)

# imprimimos el valor mínimo de cada fila de la matriz
print(matriz.min(1), "--> valor mínimo x fila")
print("-"*10)

# imprimimos el índice del valor mínimo de cada fila de la matriz
print(matriz.argmin(1), "--> indice de columna del valor mínimo para cada fila de la matriz")
print("="*10)

# obtenemos el rango de la matriz (valor máximo - valor mínimo)
print(matriz.ptp(1), "--> valor ptp de la matriz por cada fila de la matriz")
print("="*10)

# obtenemos el percentil 50 (mediana) de la matriz
print(np.sort(matriz,1), "--> arreglo ordenado de menor a mayor por cada fila")
print(np.percentile(matriz,50), "--> percentil 50 del arreglo (mediana)")

# obtenemos la mediana de la matriz con la función median de numpy
print(np.median(matriz), "--> mediana del arreglo")

# imprimimos la desviación estándar de la matriz
print(np.std(matriz), "--> desviación estandar")

# imprimimos la varianza de la matriz
print(np.var(arr), "--> varianza")

# imprimimos el promedio (media) de la matriz
print(np.mean(matriz), "--> promedio")

[[ 3 15  1 14 15]
 [ 7 10 11 10 15]]
[15 15] --> valor máximo x fila
----------
[1 4] --> indice de columna del valor máximo para cada fila de la matriz
[1 7] --> valor mínimo x fila
----------
[2 0] --> indice de columna del valor mínimo para cada fila de la matriz
[14  8] --> valor ptp de la matriz por cada fila de la matriz
[[ 1  3 14 15 15]
 [ 7 10 10 11 15]] --> arreglo ordenado de menor a mayor por cada fila
10.5 --> percentil 50 del arreglo (mediana)
10.5 --> mediana del arreglo
4.805205510693585 --> desviación estandar
23.089999999999996 --> varianza
10.1 --> promedio


Concatenate

In [8]:
a = np.array([[1,2], [3,4]])
b = np.array([4,6])

print(a)
print(b)

np.concatenate((a,b), axis=0)

[[1 2]
 [3 4]]
[4 6]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

El error que se recibe es debido a que **np.concatenate** espera que ambos arrays tengan el mismo número de dimensiones. En este caso, **"a"** tiene dos dimensiones (es un array de dos filas y dos columnas), mientras que **"b"** tiene solo una dimensión (es un array de dos elementos).

Verifiquemos las dimenciones de **"a"** y **"b"**...

In [ ]:
print(a.ndim, "--> Dimensión de A")
print(b.ndim, "--> Dimensión de B")

Para solucionar este problema, puedes hacer una de las siguientes cosas:

1. Convertir b en un array de dos dimensiones, de la siguiente manera: **b = np.array([[4], [6]])**
2. Expandir las dimensiones de b a dos, de la siguiente manera: **b = np.expand_dims(b, axis=0)**
3. Usar la función vstack en lugar de concatenate, que permite concatenar dos arrays con diferentes números de dimensiones: **np.vstack((a, b))**

In [30]:
a = np.array([[1,2], [3,4]])
b = np.array([4,6])

# Expandir b a dos dimensiones
b = np.expand_dims(b, axis=0)

print(a, "--> a")
print(b, "--> b expandido")
print("-"*10)

# Concatenar a con b.
c = np.concatenate((a,b), axis=0)
print(c, "--> c")
print("-"*10)

# Concatenar la traspuesta de c con la transpuesta de b en el eje 1
print(c.T, "--> c Transpuesta")
print(b.T, "--> b Transpuesta")
print("-")
d = np.concatenate((c.T,b.T), axis=1)
print(d, "--> d")



[[1 2]
 [3 4]] --> a
[[4 6]] --> b expandido
----------
[[1 2]
 [3 4]
 [4 6]] --> c
----------
[[1 3 4]
 [2 4 6]] --> c Transpuesta
[[4]
 [6]] --> b Transpuesta
-
[[1 3 4 4]
 [2 4 6 6]] --> d


En el codigo anterior, en la primera línea, se importa NumPy y se le da el alias "np". A continuación, se crean dos arreglos de NumPy, "a" y "b", con los valores especificados.

Luego, se usa la función "expand_dims" de NumPy para expandir el arreglo "b" a dos dimensiones. Esto se hace especificando el eje "axis = 0" como argumento de la función. Esto agrega una dimensión adicional al principio del arreglo "b", lo que lo convierte en una matriz de 2 filas y 1 columna en lugar de un vector de longitud 2.

A continuación, se imprimen los valores de "a" y "b" expandido para ver cómo han cambiado.

Luego, se usa la función "concatenate" de NumPy para concatenar los arreglos "a" y "b" en el eje "axis = 0". Esto combina los arreglos "a" y "b" en un solo arreglo multidimensional, con "a" en la parte superior y "b" debajo de él. El resultado se almacena en el arreglo "c".

Finalmente, se usa la función "concatenate" de nuevo para concatenar la traspuesta de "c" con la traspuesta de "b" en el eje "axis = 1". La traspuesta de un arreglo es otro arreglo que tiene las filas y columnas del arreglo original intercambiadas. Por lo tanto, al concatenar la traspuesta de "c" con la traspuesta de "b", se están concatenando las columnas de "c" con las filas de "b". El resultado se almacena en el arreglo "d".