In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
trozo_de_arr = arr[0:6]
print(trozo_de_arr)

[0 1 2 3 4 5]


In [4]:
trozo_de_arr[:] = 0
print(trozo_de_arr)

[0 0 0 0 0 0]


In [5]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Se dañó el arreglo!!!


In [6]:
arr_copy = arr.copy()
print(arr_copy)

arr_copy[:] = 100
print(arr_copy)

print(arr)

[ 0  0  0  0  0  0  6  7  8  9 10]
[100 100 100 100 100 100 100 100 100 100 100]
[ 0  0  0  0  0  0  6  7  8  9 10]


Se mantuvo la integridad de "arr". !!!